version: 3

tasks:
  build:
    desc: Build the app
    cmds:
      - GOFLAGS=-mod=mod go build -o bin/tmf-service src/main.go

  build.win32:
    desc: Build the app for Win 32 bits
    cmds:
      - GOOS=windows GOARCH=386 go build -o bin/tmf-service-win-386 src/main.go

  build.win64:
    desc: Build the app for Win 64 bits
    cmds:
      - GOOS=windows GOARCH=amd64 go build -o bin/tmf-service-win-64 src/main.go

  build.linux64:
    desc: Build the app for Linux 64 bits
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o bin/tmf-service-linux-64 src/main.go

  build.linux32:
    desc: Build the app for Linux 32 bits
    cmds:
      - GOOS=linux GOARCH=386 go build -o bin/tmf-service-linux-386 src/main.go

  run.web-run-server:
    desc: Run the app
    cmds:
      - GOFLAGS=-mod=mod go build -o bin/tmf-service main.go
      - GOFLAGS=-mod=mod go run main.go web-server

  swagger.doc.tmf638.v4_0:
    desc: "Swagger Documentation for TMF638 v4.0 "
    cmds:
      - docker run -i yousan/swagger-yaml-to-html < internal/pkg/tmf-service-inventory/swagger/tmf638v4_0/TMF638_Service_Inventory_Management_API_v4.0.0_swagger.json > internal/pkg/tmf-service-inventory/swagger/tmf638v4_0/doc/index.html

  swagger.validate.tmf638.v4_0:
    desc: Validate swagger
    cmds:
      - swagger validate internal/pkg/tmf-service-inventory/swagger/tmf638v4_0/TMF638_Service_Inventory_Management_API_v4.0.0_swagger.json
  swagger.gen.tmf638.v4_0:
    desc: Generate Go code
    cmds:
      - GOFLAGS=-mod=mod go generate github.com/MxelA/tmf-service github.com/MxelA/tmf-service/internal/pkg/tmf-service-inventory/swagger/tmf638v4_0

  swagger.validate.tmf638.v4_2:
    desc: Validate swagger
    cmds:
      - swagger validate internal/pkg/tmf-service-inventory/swagger/tmf638v4_2/TMF638_Service_Inventory_Management_API_v4.2.0_beta_swagger.json
  swagger.gen.tmf638.v4_2:
    desc: Generate Go code
    cmds:
      - GOFLAGS=-mod=mod go generate github.com/MxelA/tmf-service github.com/MxelA/tmf-service/internal/pkg/tmf-service-inventory/swagger/tmf638v4_2

  swagger.doc.tmf638.v4_2:
    desc: "Swagger Documentation for TMF638 v4.2 "
    cmds:
      - docker run -i yousan/swagger-yaml-to-html < internal/pkg/tmf-service-inventory/swagger/tmf638v4_2/TMF638_Service_Inventory_Management_API_v4.2.0_beta_swagger.json > internal/pkg/tmf-service-inventory/swagger/tmf638v4_2/doc/index.html

  oapi-codegen.gen.v5:
    desc: Generate Go code
    cmds:
      - GOFLAGS=-mod=mod go generate github.com/MxelA/tmf-service github.com/MxelA/tmf-service/src/oapi_codegen/tmf638v5