// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Milestone Milestone represents an action or event marking a significant change or stage in a process like an order process.
//
// swagger:model Milestone
type Milestone struct {

	// When sub-classing, this defines the super-class
	AtBaseType *string `json:"@baseType,omitempty" bson:"@baseType,omitempty"`

	// A URI to a JSON-Schema file that defines additional attributes and relationships
	// Format: uri
	AtSchemaLocation *strfmt.URI `json:"@schemaLocation,omitempty" bson:"@schemaLocation,omitempty"`

	// When sub-classing, this defines the sub-class Extensible name
	AtType *string `json:"@type,omitempty" bson:"@type,omitempty"`

	// free-text description of the Milestone
	Description *string `json:"description,omitempty" bson:"description,omitempty"`

	// identifier of the Milestone
	ID *string `json:"id,omitempty" bson:"id,omitempty"`

	// A string represents the message of the milestone
	Message *string `json:"message,omitempty" bson:"message,omitempty"`

	// A date time( DateTime). The date that the milestone happens
	// Format: date-time
	MilestoneDate *strfmt.DateTime `json:"milestoneDate,omitempty" bson:"milestoneDate,omitempty"`

	// A string used to give a name to the milestone
	Name *string `json:"name,omitempty" bson:"name,omitempty"`

	// The milestone status
	Status *string `json:"status,omitempty" bson:"status,omitempty"`
}

// Validate validates this milestone
func (m *Milestone) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAtSchemaLocation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMilestoneDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Milestone) validateAtSchemaLocation(formats strfmt.Registry) error {
	if swag.IsZero(m.AtSchemaLocation) { // not required
		return nil
	}

	if err := validate.FormatOf("@schemaLocation", "body", "uri", m.AtSchemaLocation.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Milestone) validateMilestoneDate(formats strfmt.Registry) error {
	if swag.IsZero(m.MilestoneDate) { // not required
		return nil
	}

	if err := validate.FormatOf("milestoneDate", "body", "date-time", m.MilestoneDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this milestone based on context it is used
func (m *Milestone) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Milestone) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Milestone) UnmarshalBinary(b []byte) error {
	var res Milestone
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
