// Code generated by go-swagger; DO NOT EDIT.

package notification_listeners_client_side

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MxelA/tmf-service/internal/pkg/tmf-service-order/swagger/tmf641v4_2/server/models"
)

// Alex Server response
// ListenToCancelServiceOrderInformationRequiredEventCreatedCode is the HTTP code returned for type ListenToCancelServiceOrderInformationRequiredEventCreated
const ListenToCancelServiceOrderInformationRequiredEventCreatedCode int = 201

/*
ListenToCancelServiceOrderInformationRequiredEventCreated Notified

swagger:response listenToCancelServiceOrderInformationRequiredEventCreated
*/
type ListenToCancelServiceOrderInformationRequiredEventCreated struct {

	/*
	  In: Body
	*/
	Payload *models.EventSubscription `json:"body,omitempty"`
}

type ListenToCancelServiceOrderInformationRequiredEventCreatedRaw struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewListenToCancelServiceOrderInformationRequiredEventCreated creates ListenToCancelServiceOrderInformationRequiredEventCreated with default headers values
func NewListenToCancelServiceOrderInformationRequiredEventCreated() *ListenToCancelServiceOrderInformationRequiredEventCreated {

	return &ListenToCancelServiceOrderInformationRequiredEventCreated{}
}

// NewListenToCancelServiceOrderInformationRequiredEventCreated creates ListenToCancelServiceOrderInformationRequiredEventCreatedRaw with default headers values
func NewListenToCancelServiceOrderInformationRequiredEventCreatedRaw() *ListenToCancelServiceOrderInformationRequiredEventCreatedRaw {

	return &ListenToCancelServiceOrderInformationRequiredEventCreatedRaw{}
}

// WithPayload adds the payload to the listen to cancel service order information required event created response
func (o *ListenToCancelServiceOrderInformationRequiredEventCreated) WithPayload(payload *models.EventSubscription) *ListenToCancelServiceOrderInformationRequiredEventCreated {
	o.Payload = payload
	return o
}

// WithPayload adds the payload to the listen to cancel service order information required event created response
func (o *ListenToCancelServiceOrderInformationRequiredEventCreatedRaw) WithPayload(payload interface{}) *ListenToCancelServiceOrderInformationRequiredEventCreatedRaw {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to cancel service order information required event created response
func (o *ListenToCancelServiceOrderInformationRequiredEventCreated) SetPayload(payload *models.EventSubscription) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToCancelServiceOrderInformationRequiredEventCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WriteResponseRaw to the client
func (o *ListenToCancelServiceOrderInformationRequiredEventCreatedRaw) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// Alex Server response
// ListenToCancelServiceOrderInformationRequiredEventBadRequestCode is the HTTP code returned for type ListenToCancelServiceOrderInformationRequiredEventBadRequest
const ListenToCancelServiceOrderInformationRequiredEventBadRequestCode int = 400

/*
ListenToCancelServiceOrderInformationRequiredEventBadRequest Bad Request

swagger:response listenToCancelServiceOrderInformationRequiredEventBadRequest
*/
type ListenToCancelServiceOrderInformationRequiredEventBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

type ListenToCancelServiceOrderInformationRequiredEventBadRequestRaw struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewListenToCancelServiceOrderInformationRequiredEventBadRequest creates ListenToCancelServiceOrderInformationRequiredEventBadRequest with default headers values
func NewListenToCancelServiceOrderInformationRequiredEventBadRequest() *ListenToCancelServiceOrderInformationRequiredEventBadRequest {

	return &ListenToCancelServiceOrderInformationRequiredEventBadRequest{}
}

// NewListenToCancelServiceOrderInformationRequiredEventBadRequest creates ListenToCancelServiceOrderInformationRequiredEventBadRequestRaw with default headers values
func NewListenToCancelServiceOrderInformationRequiredEventBadRequestRaw() *ListenToCancelServiceOrderInformationRequiredEventBadRequestRaw {

	return &ListenToCancelServiceOrderInformationRequiredEventBadRequestRaw{}
}

// WithPayload adds the payload to the listen to cancel service order information required event bad request response
func (o *ListenToCancelServiceOrderInformationRequiredEventBadRequest) WithPayload(payload *models.Error) *ListenToCancelServiceOrderInformationRequiredEventBadRequest {
	o.Payload = payload
	return o
}

// WithPayload adds the payload to the listen to cancel service order information required event bad request response
func (o *ListenToCancelServiceOrderInformationRequiredEventBadRequestRaw) WithPayload(payload interface{}) *ListenToCancelServiceOrderInformationRequiredEventBadRequestRaw {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to cancel service order information required event bad request response
func (o *ListenToCancelServiceOrderInformationRequiredEventBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToCancelServiceOrderInformationRequiredEventBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WriteResponseRaw to the client
func (o *ListenToCancelServiceOrderInformationRequiredEventBadRequestRaw) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// Alex Server response
// ListenToCancelServiceOrderInformationRequiredEventUnauthorizedCode is the HTTP code returned for type ListenToCancelServiceOrderInformationRequiredEventUnauthorized
const ListenToCancelServiceOrderInformationRequiredEventUnauthorizedCode int = 401

/*
ListenToCancelServiceOrderInformationRequiredEventUnauthorized Unauthorized

swagger:response listenToCancelServiceOrderInformationRequiredEventUnauthorized
*/
type ListenToCancelServiceOrderInformationRequiredEventUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

type ListenToCancelServiceOrderInformationRequiredEventUnauthorizedRaw struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewListenToCancelServiceOrderInformationRequiredEventUnauthorized creates ListenToCancelServiceOrderInformationRequiredEventUnauthorized with default headers values
func NewListenToCancelServiceOrderInformationRequiredEventUnauthorized() *ListenToCancelServiceOrderInformationRequiredEventUnauthorized {

	return &ListenToCancelServiceOrderInformationRequiredEventUnauthorized{}
}

// NewListenToCancelServiceOrderInformationRequiredEventUnauthorized creates ListenToCancelServiceOrderInformationRequiredEventUnauthorizedRaw with default headers values
func NewListenToCancelServiceOrderInformationRequiredEventUnauthorizedRaw() *ListenToCancelServiceOrderInformationRequiredEventUnauthorizedRaw {

	return &ListenToCancelServiceOrderInformationRequiredEventUnauthorizedRaw{}
}

// WithPayload adds the payload to the listen to cancel service order information required event unauthorized response
func (o *ListenToCancelServiceOrderInformationRequiredEventUnauthorized) WithPayload(payload *models.Error) *ListenToCancelServiceOrderInformationRequiredEventUnauthorized {
	o.Payload = payload
	return o
}

// WithPayload adds the payload to the listen to cancel service order information required event unauthorized response
func (o *ListenToCancelServiceOrderInformationRequiredEventUnauthorizedRaw) WithPayload(payload interface{}) *ListenToCancelServiceOrderInformationRequiredEventUnauthorizedRaw {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to cancel service order information required event unauthorized response
func (o *ListenToCancelServiceOrderInformationRequiredEventUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToCancelServiceOrderInformationRequiredEventUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WriteResponseRaw to the client
func (o *ListenToCancelServiceOrderInformationRequiredEventUnauthorizedRaw) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// Alex Server response
// ListenToCancelServiceOrderInformationRequiredEventForbiddenCode is the HTTP code returned for type ListenToCancelServiceOrderInformationRequiredEventForbidden
const ListenToCancelServiceOrderInformationRequiredEventForbiddenCode int = 403

/*
ListenToCancelServiceOrderInformationRequiredEventForbidden Forbidden

swagger:response listenToCancelServiceOrderInformationRequiredEventForbidden
*/
type ListenToCancelServiceOrderInformationRequiredEventForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

type ListenToCancelServiceOrderInformationRequiredEventForbiddenRaw struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewListenToCancelServiceOrderInformationRequiredEventForbidden creates ListenToCancelServiceOrderInformationRequiredEventForbidden with default headers values
func NewListenToCancelServiceOrderInformationRequiredEventForbidden() *ListenToCancelServiceOrderInformationRequiredEventForbidden {

	return &ListenToCancelServiceOrderInformationRequiredEventForbidden{}
}

// NewListenToCancelServiceOrderInformationRequiredEventForbidden creates ListenToCancelServiceOrderInformationRequiredEventForbiddenRaw with default headers values
func NewListenToCancelServiceOrderInformationRequiredEventForbiddenRaw() *ListenToCancelServiceOrderInformationRequiredEventForbiddenRaw {

	return &ListenToCancelServiceOrderInformationRequiredEventForbiddenRaw{}
}

// WithPayload adds the payload to the listen to cancel service order information required event forbidden response
func (o *ListenToCancelServiceOrderInformationRequiredEventForbidden) WithPayload(payload *models.Error) *ListenToCancelServiceOrderInformationRequiredEventForbidden {
	o.Payload = payload
	return o
}

// WithPayload adds the payload to the listen to cancel service order information required event forbidden response
func (o *ListenToCancelServiceOrderInformationRequiredEventForbiddenRaw) WithPayload(payload interface{}) *ListenToCancelServiceOrderInformationRequiredEventForbiddenRaw {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to cancel service order information required event forbidden response
func (o *ListenToCancelServiceOrderInformationRequiredEventForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToCancelServiceOrderInformationRequiredEventForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WriteResponseRaw to the client
func (o *ListenToCancelServiceOrderInformationRequiredEventForbiddenRaw) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// Alex Server response
// ListenToCancelServiceOrderInformationRequiredEventNotFoundCode is the HTTP code returned for type ListenToCancelServiceOrderInformationRequiredEventNotFound
const ListenToCancelServiceOrderInformationRequiredEventNotFoundCode int = 404

/*
ListenToCancelServiceOrderInformationRequiredEventNotFound Not Found

swagger:response listenToCancelServiceOrderInformationRequiredEventNotFound
*/
type ListenToCancelServiceOrderInformationRequiredEventNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

type ListenToCancelServiceOrderInformationRequiredEventNotFoundRaw struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewListenToCancelServiceOrderInformationRequiredEventNotFound creates ListenToCancelServiceOrderInformationRequiredEventNotFound with default headers values
func NewListenToCancelServiceOrderInformationRequiredEventNotFound() *ListenToCancelServiceOrderInformationRequiredEventNotFound {

	return &ListenToCancelServiceOrderInformationRequiredEventNotFound{}
}

// NewListenToCancelServiceOrderInformationRequiredEventNotFound creates ListenToCancelServiceOrderInformationRequiredEventNotFoundRaw with default headers values
func NewListenToCancelServiceOrderInformationRequiredEventNotFoundRaw() *ListenToCancelServiceOrderInformationRequiredEventNotFoundRaw {

	return &ListenToCancelServiceOrderInformationRequiredEventNotFoundRaw{}
}

// WithPayload adds the payload to the listen to cancel service order information required event not found response
func (o *ListenToCancelServiceOrderInformationRequiredEventNotFound) WithPayload(payload *models.Error) *ListenToCancelServiceOrderInformationRequiredEventNotFound {
	o.Payload = payload
	return o
}

// WithPayload adds the payload to the listen to cancel service order information required event not found response
func (o *ListenToCancelServiceOrderInformationRequiredEventNotFoundRaw) WithPayload(payload interface{}) *ListenToCancelServiceOrderInformationRequiredEventNotFoundRaw {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to cancel service order information required event not found response
func (o *ListenToCancelServiceOrderInformationRequiredEventNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToCancelServiceOrderInformationRequiredEventNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WriteResponseRaw to the client
func (o *ListenToCancelServiceOrderInformationRequiredEventNotFoundRaw) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// Alex Server response
// ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowedCode is the HTTP code returned for type ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowed
const ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowedCode int = 405

/*
ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowed Method Not allowed

swagger:response listenToCancelServiceOrderInformationRequiredEventMethodNotAllowed
*/
type ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

type ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowedRaw struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewListenToCancelServiceOrderInformationRequiredEventMethodNotAllowed creates ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowed with default headers values
func NewListenToCancelServiceOrderInformationRequiredEventMethodNotAllowed() *ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowed {

	return &ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowed{}
}

// NewListenToCancelServiceOrderInformationRequiredEventMethodNotAllowed creates ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowedRaw with default headers values
func NewListenToCancelServiceOrderInformationRequiredEventMethodNotAllowedRaw() *ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowedRaw {

	return &ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowedRaw{}
}

// WithPayload adds the payload to the listen to cancel service order information required event method not allowed response
func (o *ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowed) WithPayload(payload *models.Error) *ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowed {
	o.Payload = payload
	return o
}

// WithPayload adds the payload to the listen to cancel service order information required event method not allowed response
func (o *ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowedRaw) WithPayload(payload interface{}) *ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowedRaw {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to cancel service order information required event method not allowed response
func (o *ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WriteResponseRaw to the client
func (o *ListenToCancelServiceOrderInformationRequiredEventMethodNotAllowedRaw) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// Alex Server response
// ListenToCancelServiceOrderInformationRequiredEventConflictCode is the HTTP code returned for type ListenToCancelServiceOrderInformationRequiredEventConflict
const ListenToCancelServiceOrderInformationRequiredEventConflictCode int = 409

/*
ListenToCancelServiceOrderInformationRequiredEventConflict Conflict

swagger:response listenToCancelServiceOrderInformationRequiredEventConflict
*/
type ListenToCancelServiceOrderInformationRequiredEventConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

type ListenToCancelServiceOrderInformationRequiredEventConflictRaw struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewListenToCancelServiceOrderInformationRequiredEventConflict creates ListenToCancelServiceOrderInformationRequiredEventConflict with default headers values
func NewListenToCancelServiceOrderInformationRequiredEventConflict() *ListenToCancelServiceOrderInformationRequiredEventConflict {

	return &ListenToCancelServiceOrderInformationRequiredEventConflict{}
}

// NewListenToCancelServiceOrderInformationRequiredEventConflict creates ListenToCancelServiceOrderInformationRequiredEventConflictRaw with default headers values
func NewListenToCancelServiceOrderInformationRequiredEventConflictRaw() *ListenToCancelServiceOrderInformationRequiredEventConflictRaw {

	return &ListenToCancelServiceOrderInformationRequiredEventConflictRaw{}
}

// WithPayload adds the payload to the listen to cancel service order information required event conflict response
func (o *ListenToCancelServiceOrderInformationRequiredEventConflict) WithPayload(payload *models.Error) *ListenToCancelServiceOrderInformationRequiredEventConflict {
	o.Payload = payload
	return o
}

// WithPayload adds the payload to the listen to cancel service order information required event conflict response
func (o *ListenToCancelServiceOrderInformationRequiredEventConflictRaw) WithPayload(payload interface{}) *ListenToCancelServiceOrderInformationRequiredEventConflictRaw {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to cancel service order information required event conflict response
func (o *ListenToCancelServiceOrderInformationRequiredEventConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToCancelServiceOrderInformationRequiredEventConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WriteResponseRaw to the client
func (o *ListenToCancelServiceOrderInformationRequiredEventConflictRaw) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// Alex Server response
// ListenToCancelServiceOrderInformationRequiredEventInternalServerErrorCode is the HTTP code returned for type ListenToCancelServiceOrderInformationRequiredEventInternalServerError
const ListenToCancelServiceOrderInformationRequiredEventInternalServerErrorCode int = 500

/*
ListenToCancelServiceOrderInformationRequiredEventInternalServerError Internal Server Error

swagger:response listenToCancelServiceOrderInformationRequiredEventInternalServerError
*/
type ListenToCancelServiceOrderInformationRequiredEventInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

type ListenToCancelServiceOrderInformationRequiredEventInternalServerErrorRaw struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewListenToCancelServiceOrderInformationRequiredEventInternalServerError creates ListenToCancelServiceOrderInformationRequiredEventInternalServerError with default headers values
func NewListenToCancelServiceOrderInformationRequiredEventInternalServerError() *ListenToCancelServiceOrderInformationRequiredEventInternalServerError {

	return &ListenToCancelServiceOrderInformationRequiredEventInternalServerError{}
}

// NewListenToCancelServiceOrderInformationRequiredEventInternalServerError creates ListenToCancelServiceOrderInformationRequiredEventInternalServerErrorRaw with default headers values
func NewListenToCancelServiceOrderInformationRequiredEventInternalServerErrorRaw() *ListenToCancelServiceOrderInformationRequiredEventInternalServerErrorRaw {

	return &ListenToCancelServiceOrderInformationRequiredEventInternalServerErrorRaw{}
}

// WithPayload adds the payload to the listen to cancel service order information required event internal server error response
func (o *ListenToCancelServiceOrderInformationRequiredEventInternalServerError) WithPayload(payload *models.Error) *ListenToCancelServiceOrderInformationRequiredEventInternalServerError {
	o.Payload = payload
	return o
}

// WithPayload adds the payload to the listen to cancel service order information required event internal server error response
func (o *ListenToCancelServiceOrderInformationRequiredEventInternalServerErrorRaw) WithPayload(payload interface{}) *ListenToCancelServiceOrderInformationRequiredEventInternalServerErrorRaw {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the listen to cancel service order information required event internal server error response
func (o *ListenToCancelServiceOrderInformationRequiredEventInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListenToCancelServiceOrderInformationRequiredEventInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WriteResponseRaw to the client
func (o *ListenToCancelServiceOrderInformationRequiredEventInternalServerErrorRaw) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
