// Code generated by go-swagger; DO NOT EDIT.

package service_order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewPatchServiceOrderParams creates a new PatchServiceOrderParams object
//
// There are no default values defined in the spec.
func NewPatchServiceOrderParams() PatchServiceOrderParams {

	return PatchServiceOrderParams{}
}

// PatchServiceOrderParams contains all the bound params for the patch service order operation
// typically these are obtained from a http.Request
//
// swagger:parameters patchServiceOrder
type PatchServiceOrderParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Identifier of the ServiceOrder
	  Required: true
	  In: path
	*/
	ID string
	/*The ServiceOrder to be updated
	  Required: true
	  In: body
	*/
	ServiceOrder interface{}
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPatchServiceOrderParams() beforehand.
func (o *PatchServiceOrderParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body interface{}
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("serviceOrder", "body", ""))
			} else {
				res = append(res, errors.NewParseError("serviceOrder", "body", "", err))
			}
		} else {
			// no validation on generic interface
			o.ServiceOrder = body
		}
	} else {
		res = append(res, errors.Required("serviceOrder", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindID binds and validates parameter ID from path.
func (o *PatchServiceOrderParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ID = raw

	return nil
}
