// Code generated by go-swagger; DO NOT EDIT.

package notification_listeners_client_side

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListenToServiceAttributeValueChangeEventHandlerFunc turns a function with the right signature into a listen to service attribute value change event handler
type ListenToServiceAttributeValueChangeEventHandlerFunc func(ListenToServiceAttributeValueChangeEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListenToServiceAttributeValueChangeEventHandlerFunc) Handle(params ListenToServiceAttributeValueChangeEventParams) middleware.Responder {
	return fn(params)
}

// ListenToServiceAttributeValueChangeEventHandler interface for that can handle valid listen to service attribute value change event params
type ListenToServiceAttributeValueChangeEventHandler interface {
	Handle(ListenToServiceAttributeValueChangeEventParams) middleware.Responder
}

// NewListenToServiceAttributeValueChangeEvent creates a new http.Handler for the listen to service attribute value change event operation
func NewListenToServiceAttributeValueChangeEvent(ctx *middleware.Context, handler ListenToServiceAttributeValueChangeEventHandler) *ListenToServiceAttributeValueChangeEvent {
	return &ListenToServiceAttributeValueChangeEvent{Context: ctx, Handler: handler}
}

/*
	ListenToServiceAttributeValueChangeEvent swagger:route POST /listener/serviceAttributeValueChangeEvent notification listeners (client side) listenToServiceAttributeValueChangeEvent

# Client listener for entity ServiceAttributeValueChangeEvent

Example of a client listener for receiving the notification ServiceAttributeValueChangeEvent
*/
type ListenToServiceAttributeValueChangeEvent struct {
	Context *middleware.Context
	Handler ListenToServiceAttributeValueChangeEventHandler
}

func (o *ListenToServiceAttributeValueChangeEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListenToServiceAttributeValueChangeEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
