// Code generated by go-swagger; DO NOT EDIT.

package notification_listeners_client_side

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListenToServiceCreateEventHandlerFunc turns a function with the right signature into a listen to service create event handler
type ListenToServiceCreateEventHandlerFunc func(ListenToServiceCreateEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListenToServiceCreateEventHandlerFunc) Handle(params ListenToServiceCreateEventParams) middleware.Responder {
	return fn(params)
}

// ListenToServiceCreateEventHandler interface for that can handle valid listen to service create event params
type ListenToServiceCreateEventHandler interface {
	Handle(ListenToServiceCreateEventParams) middleware.Responder
}

// NewListenToServiceCreateEvent creates a new http.Handler for the listen to service create event operation
func NewListenToServiceCreateEvent(ctx *middleware.Context, handler ListenToServiceCreateEventHandler) *ListenToServiceCreateEvent {
	return &ListenToServiceCreateEvent{Context: ctx, Handler: handler}
}

/*
	ListenToServiceCreateEvent swagger:route POST /listener/serviceCreateEvent notification listeners (client side) listenToServiceCreateEvent

# Client listener for entity ServiceCreateEvent

Example of a client listener for receiving the notification ServiceCreateEvent
*/
type ListenToServiceCreateEvent struct {
	Context *middleware.Context
	Handler ListenToServiceCreateEventHandler
}

func (o *ListenToServiceCreateEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListenToServiceCreateEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
